### ISSUE TITLE
Does not create schematic, can't find "cssselect"

### ISSUE THREAD

**Issue by FrightRisk** [revolt-randy/Fritzing-Schematic-an-Inkscape-Extension.#3]
I am using Inkscape version Inkscape 1.2.1 (9c6d41e410, 2022-07-14), copied the files to the extensions folder and rebooted. When I try to run the extension, I get this log window:

Traceback (most recent call last):
  File "C:\Users\Fred\AppData\Roaming\inkscape\extensions\fritzing-schematic.py", line 35, in <module>
    import inkex
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\__init__.py", line 11, in <module>
    from .extensions import *
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\extensions.py", line 34, in <module>
    from .elements import (
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\elements\__init__.py", line 10, in <module>
    from ._base import ShapeElement, BaseElement
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\elements\_base.py", line 38, in <module>
    from ..styles import Style, Classes
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\styles.py", line 33, in <module>
    from .css import ConditionalRule
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\css.py", line 27, in <module>
    import cssselect
ModuleNotFoundError: No module named 'cssselect'

**Comment by FrightRisk** [comment]
It looks like this is a bug in Inkscape 1.2. Supposedly fixed in a beta version. I just did:

pip install cssselect
pip install numpy

and it works.

**Comment by revolt-randy** [comment]
What OS are you using?

There was an error in the fritzing-schematic.inx that caused crashes on Win10 and I fixed that 12 days ago, so if you haven't downloaded the extension in the past 12 days, you may want to. Not likely the cause of your problem. 
I see some Inkscape bug reports of css errors on Linux OS, and some reports of numpy issues on Mac OS.
